/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CourseFormRouteImport } from './routes/courseForm'
import { Route as IndexRouteImport } from './routes/index'

const CourseFormRoute = CourseFormRouteImport.update({
  id: '/courseForm',
  path: '/courseForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courseForm': typeof CourseFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courseForm': typeof CourseFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courseForm': typeof CourseFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courseForm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courseForm'
  id: '__root__' | '/' | '/courseForm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseFormRoute: typeof CourseFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courseForm': {
      id: '/courseForm'
      path: '/courseForm'
      fullPath: '/courseForm'
      preLoaderRoute: typeof CourseFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseFormRoute: CourseFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
